services:
    _defaults:
        autowire: true
        autoconfigure: true

    Becklyn\Menu\:
        resource: '../../*'
        exclude: '../../{Exception,Node,Resources,BecklynMenuBundle.php}'

    Becklyn\Menu\Renderer\MenuRenderer:
        $visitors: !tagged becklyn.menu.visitor

    Becklyn\Menu\Visitor\CoreVisitor:
        tags:
            - { name: becklyn.menu.visitor, priority: -1000 }

    Becklyn\Menu\Visitor\VoterVisitor:
        arguments:
            $voters: !tagged becklyn.menu.voter
        tags:
            - { name: becklyn.menu.visitor, priority: -1500 }
